-- Database Schema v1 FINAL — PostgreSQL / Flyway executable baseline.
-- Derived from docs/database/schema_v1.dbml; technical conventions accepted by DEC-070.
-- Do not add business entities, fields, statuses, or validations without source reconciliation.

CREATE TABLE "app_user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar NOT NULL,
  "role" varchar(40) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_app_user_role" CHECK (role IN ('REQUESTER', 'REQUEST_APPROVER', 'INVENTORY_STAFF', 'INVENTORY_APPROVER', 'WAREHOUSE_KEEPER'))
);

CREATE TABLE "material_group" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "requires_accounting" boolean NOT NULL,
  "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "material" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "material_code" varchar UNIQUE NOT NULL,
  "material_name" varchar(200) NOT NULL,
  "material_group_id" bigint NOT NULL,
  "unit" varchar(20) NOT NULL,
  "gl_code" varchar(200),
  "status" varchar(20) NOT NULL DEFAULT 'ACTIVE',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_material_unit" CHECK (unit IN ('BO', 'CAI', 'CUON', 'HOP', 'KHAY', 'MAY', 'TO', 'THUNG', 'MIENG')),
  CONSTRAINT "ck_material_gl_code_format" CHECK (gl_code IS NULL OR gl_code ~ '^[A-Za-z0-9-]+$'),
  CONSTRAINT "ck_material_status" CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE "warehouse" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_code" varchar(30) UNIQUE NOT NULL,
  "warehouse_name" varchar(50) UNIQUE NOT NULL,
  "address" varchar(200) NOT NULL,
  "note" varchar(200),
  "status" varchar(20) NOT NULL DEFAULT 'ACTIVE',
  "updated_by_user_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_warehouse_code_format" CHECK (warehouse_code ~ '^[A-Za-z0-9_]+$'),
  CONSTRAINT "ck_warehouse_name_length" CHECK (char_length(warehouse_name) BETWEEN 5 AND 50),
  CONSTRAINT "ck_warehouse_address_length" CHECK (char_length(address) BETWEEN 20 AND 200),
  CONSTRAINT "ck_warehouse_note_length" CHECK (note IS NULL OR char_length(note) <= 200),
  CONSTRAINT "ck_warehouse_status" CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE "operation_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "direction" varchar(20) NOT NULL,
  "requires_po" boolean NOT NULL,
  "requires_accounting" boolean NOT NULL,
  "default_condition" varchar(20),
  "active" boolean NOT NULL DEFAULT true,
  "display_order" int NOT NULL,
  CONSTRAINT "ck_operation_type_direction" CHECK (direction IN ('IMPORT', 'EXPORT', 'TRANSFER')),
  CONSTRAINT "ck_operation_type_default_condition" CHECK (default_condition IS NULL OR default_condition IN ('NEW', 'OLD', 'BROKEN', 'TEMP'))
);

CREATE TABLE "operation_type_material_group" (
  "operation_type_id" bigint NOT NULL,
  "material_group_id" bigint NOT NULL,
  PRIMARY KEY ("operation_type_id", "material_group_id")
);

CREATE TABLE "operation_type_condition" (
  "operation_type_id" bigint NOT NULL,
  "condition" varchar(20) NOT NULL,
  CONSTRAINT "ck_operation_type_condition_value" CHECK (condition IN ('NEW', 'OLD', 'BROKEN', 'TEMP')),
  PRIMARY KEY ("operation_type_id", "condition")
);

CREATE TABLE "reason" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "direction" varchar(20) NOT NULL,
  "requires_note" boolean NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "display_order" int NOT NULL,
  CONSTRAINT "ck_reason_direction" CHECK (direction IN ('IMPORT', 'EXPORT', 'TRANSFER'))
);

CREATE TABLE "purchase_order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "po_code" varchar(50) UNIQUE NOT NULL,
  "supplier_name" varchar(300) NOT NULL,
  "order_date" date NOT NULL,
  "first_received_at" timestamptz,
  "status" varchar(30) NOT NULL DEFAULT 'DRAFT',
  "created_by_user_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_purchase_order_status" CHECK (status IN ('DRAFT', 'OPEN', 'PARTIALLY_RECEIVED', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE "purchase_order_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_order_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "ordered_quantity" bigint NOT NULL,
  "unit_price" numeric(19,4),
  CONSTRAINT "ck_purchase_order_item_quantity" CHECK (ordered_quantity > 0),
  CONSTRAINT "ck_purchase_order_item_unit_price" CHECK (unit_price IS NULL OR unit_price > 0)
);

CREATE TABLE "warehouse_request" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_code" varchar(16) UNIQUE NOT NULL,
  "operation_type_id" bigint NOT NULL,
  "reason_id" bigint NOT NULL,
  "source_warehouse_id" bigint,
  "destination_warehouse_id" bigint,
  "purchase_order_id" bigint,
  "note" varchar(300),
  "status" varchar(30) NOT NULL DEFAULT 'DRAFT',
  "created_by_user_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_warehouse_request_code_format" CHECK (request_code ~ '^(INP|OUT|TRF)_[0-9]{8}_[0-9]{3}$'),
  CONSTRAINT "ck_warehouse_request_status" CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'CANCELLED')),
  CONSTRAINT "ck_warehouse_request_distinct_warehouses" CHECK (source_warehouse_id IS NULL OR destination_warehouse_id IS NULL OR source_warehouse_id <> destination_warehouse_id)
);

CREATE TABLE "warehouse_request_detail" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "condition" varchar(20) NOT NULL,
  "quantity" bigint NOT NULL,
  "purchase_order_item_id" bigint,
  CONSTRAINT "ck_warehouse_request_detail_condition" CHECK (condition IN ('NEW', 'OLD', 'BROKEN', 'TEMP')),
  CONSTRAINT "ck_warehouse_request_detail_quantity" CHECK (quantity > 0)
);

CREATE TABLE "stock_reservation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_detail_id" bigint UNIQUE NOT NULL,
  "warehouse_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "condition" varchar(20) NOT NULL,
  "quantity" bigint NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'ACTIVE_SOFT',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "released_at" timestamptz,
  CONSTRAINT "ck_stock_reservation_condition" CHECK (condition IN ('NEW', 'OLD', 'BROKEN', 'TEMP')),
  CONSTRAINT "ck_stock_reservation_quantity" CHECK (quantity > 0),
  CONSTRAINT "ck_stock_reservation_status" CHECK (status IN ('ACTIVE_SOFT', 'CONVERTED', 'RELEASED')),
  CONSTRAINT "ck_stock_reservation_release_time" CHECK ((status = 'ACTIVE_SOFT' AND released_at IS NULL) OR (status IN ('CONVERTED', 'RELEASED') AND released_at IS NOT NULL))
);

CREATE TABLE "warehouse_transaction" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_code" varchar(20) UNIQUE NOT NULL,
  "request_id" bigint UNIQUE NOT NULL,
  "warehouse_status" varchar(40) NOT NULL DEFAULT 'DRAFT',
  "accounting_status" varchar(30),
  "execution_note" varchar(1000),
  "physical_confirmed_at" timestamptz,
  "physical_confirmed_by_user_id" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_warehouse_transaction_code_format" CHECK (transaction_code ~ '^(GRN_INP|GDN_OUT)_[0-9]{8}_[0-9]{3}$'),
  CONSTRAINT "ck_warehouse_transaction_status" CHECK (warehouse_status IN ('DRAFT', 'SUBMITTED', 'READY_FOR_CONFIRMATION', 'COMPLETED', 'REJECTED')),
  CONSTRAINT "ck_warehouse_transaction_accounting_status" CHECK (accounting_status IS NULL OR accounting_status IN ('NOT_REQUIRED', 'PENDING')),
  CONSTRAINT "ck_warehouse_transaction_completion" CHECK ((warehouse_status = 'COMPLETED' AND accounting_status IN ('NOT_REQUIRED', 'PENDING') AND physical_confirmed_at IS NOT NULL AND physical_confirmed_by_user_id IS NOT NULL) OR (warehouse_status <> 'COMPLETED' AND accounting_status IS NULL AND physical_confirmed_at IS NULL AND physical_confirmed_by_user_id IS NULL))
);

CREATE TABLE "warehouse_transaction_detail" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" bigint NOT NULL,
  "request_detail_id" bigint UNIQUE NOT NULL
);

CREATE TABLE "issue_lot_allocation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_detail_id" bigint NOT NULL,
  "inventory_lot_id" bigint NOT NULL,
  "allocated_quantity" bigint NOT NULL,
  "allocated_unit_price" numeric(19,4),
  CONSTRAINT "ck_issue_lot_allocation_quantity" CHECK (allocated_quantity > 0),
  CONSTRAINT "ck_issue_lot_allocation_price" CHECK (allocated_unit_price IS NULL OR allocated_unit_price > 0)
);

CREATE TABLE "inventory_lot" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "condition" varchar(20) NOT NULL,
  "source_po_item_id" bigint,
  "receipt_transaction_detail_id" bigint UNIQUE,
  "source_transfer_allocation_id" bigint UNIQUE,
  "unit_price" numeric(19,4),
  "on_hand_quantity" bigint NOT NULL DEFAULT 0,
  "reserved_quantity" bigint NOT NULL DEFAULT 0,
  "received_at" timestamptz NOT NULL,
  CONSTRAINT "ck_inventory_lot_condition" CHECK (condition IN ('NEW', 'OLD', 'BROKEN', 'TEMP')),
  CONSTRAINT "ck_inventory_lot_unit_price" CHECK (unit_price IS NULL OR unit_price > 0),
  CONSTRAINT "ck_inventory_lot_on_hand" CHECK (on_hand_quantity >= 0),
  CONSTRAINT "ck_inventory_lot_reserved" CHECK (reserved_quantity >= 0 AND reserved_quantity <= on_hand_quantity),
  CONSTRAINT "ck_inventory_lot_single_origin" CHECK (NOT (receipt_transaction_detail_id IS NOT NULL AND source_transfer_allocation_id IS NOT NULL))
);

CREATE TABLE "inventory_daily_snapshot" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "snapshot_date" date NOT NULL,
  "warehouse_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "condition" varchar(20) NOT NULL,
  "on_hand_quantity" bigint NOT NULL,
  "reserved_quantity" bigint NOT NULL,
  "available_quantity" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_inventory_daily_snapshot_condition" CHECK (condition IN ('NEW', 'OLD', 'BROKEN', 'TEMP')),
  CONSTRAINT "ck_inventory_daily_snapshot_on_hand" CHECK (on_hand_quantity >= 0),
  CONSTRAINT "ck_inventory_daily_snapshot_reserved" CHECK (reserved_quantity >= 0),
  CONSTRAINT "ck_inventory_daily_snapshot_available" CHECK (available_quantity = on_hand_quantity - reserved_quantity)
);

CREATE TABLE "warehouse_transfer" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" bigint UNIQUE NOT NULL,
  "source_warehouse_id" bigint NOT NULL,
  "destination_warehouse_id" bigint NOT NULL,
  "status" varchar(40) NOT NULL DEFAULT 'DRAFT',
  "source_confirmed_at" timestamptz,
  "source_confirmed_by_user_id" bigint,
  "destination_confirmed_at" timestamptz,
  "destination_confirmed_by_user_id" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_warehouse_transfer_distinct_warehouses" CHECK (source_warehouse_id <> destination_warehouse_id),
  CONSTRAINT "ck_warehouse_transfer_status" CHECK (status IN ('DRAFT', 'SUBMITTED', 'READY_TO_TRANSFER', 'IN_TRANSIT', 'COMPLETED', 'REJECTED')),
  CONSTRAINT "ck_warehouse_transfer_confirmation" CHECK ((status IN ('DRAFT', 'SUBMITTED', 'READY_TO_TRANSFER', 'REJECTED') AND source_confirmed_at IS NULL AND source_confirmed_by_user_id IS NULL AND destination_confirmed_at IS NULL AND destination_confirmed_by_user_id IS NULL) OR (status = 'IN_TRANSIT' AND source_confirmed_at IS NOT NULL AND source_confirmed_by_user_id IS NOT NULL AND destination_confirmed_at IS NULL AND destination_confirmed_by_user_id IS NULL) OR (status = 'COMPLETED' AND source_confirmed_at IS NOT NULL AND source_confirmed_by_user_id IS NOT NULL AND destination_confirmed_at IS NOT NULL AND destination_confirmed_by_user_id IS NOT NULL))
);

CREATE TABLE "warehouse_transfer_detail" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_id" bigint NOT NULL,
  "request_detail_id" bigint UNIQUE NOT NULL
);

CREATE TABLE "transfer_lot_allocation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_detail_id" bigint NOT NULL,
  "inventory_lot_id" bigint NOT NULL,
  "allocated_quantity" bigint NOT NULL,
  "allocated_unit_price" numeric(19,4),
  CONSTRAINT "ck_transfer_lot_allocation_quantity" CHECK (allocated_quantity > 0),
  CONSTRAINT "ck_transfer_lot_allocation_price" CHECK (allocated_unit_price IS NULL OR allocated_unit_price > 0)
);

CREATE TABLE "status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aggregate_type" varchar(30) NOT NULL,
  "aggregate_id" bigint NOT NULL,
  "from_status" varchar(40),
  "to_status" varchar(40) NOT NULL,
  "action" varchar(30) NOT NULL,
  "changed_by_user_id" bigint NOT NULL,
  "comment" varchar(500),
  "changed_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_status_history_aggregate_type" CHECK (aggregate_type IN ('REQUEST', 'TRANSACTION', 'TRANSFER')),
  CONSTRAINT "ck_status_history_action" CHECK (action IN ('SUBMIT', 'CANCEL', 'APPROVE', 'REJECT', 'START_PROCESSING', 'CONFIRM_PHYSICAL', 'CONFIRM_SOURCE', 'CONFIRM_DESTINATION', 'COMPLETE'))
);

CREATE INDEX "ix_material_group_status" ON "material" ("material_group_id", "status");

CREATE UNIQUE INDEX "uk_material_active_gl_code"
  ON "material" ("gl_code")
  WHERE "status" = 'ACTIVE' AND "gl_code" IS NOT NULL;

CREATE INDEX "ix_warehouse_status_code" ON "warehouse" ("status", "warehouse_code");

CREATE INDEX "ix_operation_type_material_group_group" ON "operation_type_material_group" ("material_group_id");

CREATE INDEX "ix_purchase_order_status_date" ON "purchase_order" ("status", "order_date");

CREATE INDEX "ix_purchase_order_creator" ON "purchase_order" ("created_by_user_id");

CREATE UNIQUE INDEX "uk_purchase_order_item_material" ON "purchase_order_item" ("purchase_order_id", "material_id");

CREATE INDEX "ix_purchase_order_item_material" ON "purchase_order_item" ("material_id");

CREATE INDEX "ix_warehouse_request_creator_status" ON "warehouse_request" ("created_by_user_id", "status", "created_at");

CREATE INDEX "ix_warehouse_request_source_status" ON "warehouse_request" ("source_warehouse_id", "status");

CREATE INDEX "ix_warehouse_request_destination_status" ON "warehouse_request" ("destination_warehouse_id", "status");

CREATE INDEX "ix_warehouse_request_po_status" ON "warehouse_request" ("purchase_order_id", "status");

CREATE INDEX "ix_warehouse_request_detail_request" ON "warehouse_request_detail" ("request_id");

CREATE INDEX "ix_warehouse_request_detail_material_condition" ON "warehouse_request_detail" ("material_id", "condition");

CREATE INDEX "ix_warehouse_request_detail_po_item" ON "warehouse_request_detail" ("purchase_order_item_id");

CREATE INDEX "ix_stock_reservation_availability" ON "stock_reservation" ("warehouse_id", "material_id", "condition", "status");

CREATE INDEX "ix_warehouse_transaction_status_created" ON "warehouse_transaction" ("warehouse_status", "created_at");

CREATE INDEX "ix_warehouse_transaction_physical_time" ON "warehouse_transaction" ("physical_confirmed_at");

CREATE INDEX "ix_warehouse_transaction_detail_transaction" ON "warehouse_transaction_detail" ("transaction_id");

CREATE UNIQUE INDEX "uk_issue_lot_allocation_detail_lot" ON "issue_lot_allocation" ("transaction_detail_id", "inventory_lot_id");

CREATE INDEX "ix_issue_lot_allocation_lot" ON "issue_lot_allocation" ("inventory_lot_id");

CREATE INDEX "ix_inventory_lot_fifo" ON "inventory_lot" ("warehouse_id", "material_id", "condition", "received_at", "id");

CREATE INDEX "ix_inventory_lot_source_po_item" ON "inventory_lot" ("source_po_item_id");

CREATE UNIQUE INDEX "uk_inventory_daily_snapshot_dimension" ON "inventory_daily_snapshot" ("snapshot_date", "warehouse_id", "material_id", "condition");

CREATE INDEX "ix_inventory_daily_snapshot_report" ON "inventory_daily_snapshot" ("warehouse_id", "material_id", "condition", "snapshot_date");

CREATE INDEX "ix_warehouse_transfer_source_status" ON "warehouse_transfer" ("source_warehouse_id", "status");

CREATE INDEX "ix_warehouse_transfer_destination_status" ON "warehouse_transfer" ("destination_warehouse_id", "status");

CREATE INDEX "ix_warehouse_transfer_source_time" ON "warehouse_transfer" ("source_confirmed_at");

CREATE INDEX "ix_warehouse_transfer_destination_time" ON "warehouse_transfer" ("destination_confirmed_at");

CREATE INDEX "ix_warehouse_transfer_detail_transfer" ON "warehouse_transfer_detail" ("transfer_id");

CREATE UNIQUE INDEX "uk_transfer_lot_allocation_detail_lot" ON "transfer_lot_allocation" ("transfer_detail_id", "inventory_lot_id");

CREATE INDEX "ix_transfer_lot_allocation_lot" ON "transfer_lot_allocation" ("inventory_lot_id");

CREATE INDEX "ix_status_history_target_time" ON "status_history" ("aggregate_type", "aggregate_id", "changed_at");

CREATE INDEX "ix_status_history_actor" ON "status_history" ("changed_by_user_id");

COMMENT ON TABLE "app_user" IS 'MVP authentication user. Exactly one of five accepted business roles.';

COMMENT ON TABLE "material_group" IS 'Accounting requirement belongs to MaterialGroup, not Material.';

COMMENT ON TABLE "material" IS 'Group and material_code are immutable after create. Conditional GL requirement and active-only GL uniqueness require service/Flyway enforcement.';

COMMENT ON TABLE "warehouse" IS 'DEC-067: updated_by_user_id and updated_at represent the latest warehouse operator and time.';

COMMENT ON TABLE "operation_type_material_group" IS 'Normalized N:N mapping. Cross-table accounting consistency is enforced transactionally in the service layer.';

COMMENT ON TABLE "purchase_order_item" IS 'All items in one PO must resolve to the same MaterialGroup; conditional unit_price is enforced transactionally.';

COMMENT ON TABLE "warehouse_request" IS 'Variant-specific warehouse/PO/direction/reason rules and reason.requires_note require service validation.';

COMMENT ON TABLE "warehouse_transaction" IS 'DEC-069: accounting_status is null before physical confirmation and set only when warehouse_status becomes COMPLETED.';

COMMENT ON TABLE "warehouse_transaction_detail" IS 'DEC-070 keeps a direct immutable mapping to the approved request detail rather than duplicating material/condition/quantity.';

COMMENT ON TABLE "inventory_lot" IS 'Inventory source of truth. DEC-070 accepts two nullable origin FKs for stable Stock Card provenance.';

COMMENT ON TABLE "inventory_daily_snapshot" IS 'Quantity-only historical read model. No unit price, PO, or lot dimension.';

COMMENT ON TABLE "warehouse_transfer" IS 'DEC-068: no transfer_code. Stock Card Document Code is the linked WarehouseRequest.request_code.';

COMMENT ON TABLE "status_history" IS 'DEC-070 accepts the polymorphic target. Target existence is validated in the service transaction. DEC-073 fixes action values and comment length.';

ALTER TABLE "material" ADD CONSTRAINT "fk_material_group" FOREIGN KEY ("material_group_id") REFERENCES "material_group" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse" ADD CONSTRAINT "fk_warehouse_updated_by" FOREIGN KEY ("updated_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "operation_type_material_group" ADD CONSTRAINT "fk_operation_type_group_operation" FOREIGN KEY ("operation_type_id") REFERENCES "operation_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "operation_type_material_group" ADD CONSTRAINT "fk_operation_type_group_group" FOREIGN KEY ("material_group_id") REFERENCES "material_group" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "operation_type_condition" ADD CONSTRAINT "fk_operation_type_condition_operation" FOREIGN KEY ("operation_type_id") REFERENCES "operation_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_order" ADD CONSTRAINT "fk_purchase_order_creator" FOREIGN KEY ("created_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_order_item" ADD CONSTRAINT "fk_purchase_order_item_order" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_order_item" ADD CONSTRAINT "fk_purchase_order_item_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request" ADD CONSTRAINT "fk_request_operation_type" FOREIGN KEY ("operation_type_id") REFERENCES "operation_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request" ADD CONSTRAINT "fk_request_reason" FOREIGN KEY ("reason_id") REFERENCES "reason" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request" ADD CONSTRAINT "fk_request_source_warehouse" FOREIGN KEY ("source_warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request" ADD CONSTRAINT "fk_request_destination_warehouse" FOREIGN KEY ("destination_warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request" ADD CONSTRAINT "fk_request_purchase_order" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request" ADD CONSTRAINT "fk_request_creator" FOREIGN KEY ("created_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request_detail" ADD CONSTRAINT "fk_request_detail_request" FOREIGN KEY ("request_id") REFERENCES "warehouse_request" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request_detail" ADD CONSTRAINT "fk_request_detail_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_request_detail" ADD CONSTRAINT "fk_request_detail_po_item" FOREIGN KEY ("purchase_order_item_id") REFERENCES "purchase_order_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_reservation" ADD CONSTRAINT "fk_stock_reservation_request_detail" FOREIGN KEY ("request_detail_id") REFERENCES "warehouse_request_detail" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_reservation" ADD CONSTRAINT "fk_stock_reservation_warehouse" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_reservation" ADD CONSTRAINT "fk_stock_reservation_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transaction" ADD CONSTRAINT "fk_transaction_request" FOREIGN KEY ("request_id") REFERENCES "warehouse_request" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transaction" ADD CONSTRAINT "fk_transaction_confirmer" FOREIGN KEY ("physical_confirmed_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transaction_detail" ADD CONSTRAINT "fk_transaction_detail_transaction" FOREIGN KEY ("transaction_id") REFERENCES "warehouse_transaction" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transaction_detail" ADD CONSTRAINT "fk_transaction_detail_request_detail" FOREIGN KEY ("request_detail_id") REFERENCES "warehouse_request_detail" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "issue_lot_allocation" ADD CONSTRAINT "fk_issue_allocation_transaction_detail" FOREIGN KEY ("transaction_detail_id") REFERENCES "warehouse_transaction_detail" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "issue_lot_allocation" ADD CONSTRAINT "fk_issue_allocation_lot" FOREIGN KEY ("inventory_lot_id") REFERENCES "inventory_lot" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_lot" ADD CONSTRAINT "fk_inventory_lot_warehouse" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_lot" ADD CONSTRAINT "fk_inventory_lot_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_lot" ADD CONSTRAINT "fk_inventory_lot_po_item" FOREIGN KEY ("source_po_item_id") REFERENCES "purchase_order_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_lot" ADD CONSTRAINT "fk_inventory_lot_receipt_detail" FOREIGN KEY ("receipt_transaction_detail_id") REFERENCES "warehouse_transaction_detail" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_lot" ADD CONSTRAINT "fk_inventory_lot_transfer_allocation" FOREIGN KEY ("source_transfer_allocation_id") REFERENCES "transfer_lot_allocation" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_daily_snapshot" ADD CONSTRAINT "fk_snapshot_warehouse" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_daily_snapshot" ADD CONSTRAINT "fk_snapshot_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer" ADD CONSTRAINT "fk_transfer_request" FOREIGN KEY ("request_id") REFERENCES "warehouse_request" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer" ADD CONSTRAINT "fk_transfer_source_warehouse" FOREIGN KEY ("source_warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer" ADD CONSTRAINT "fk_transfer_destination_warehouse" FOREIGN KEY ("destination_warehouse_id") REFERENCES "warehouse" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer" ADD CONSTRAINT "fk_transfer_source_confirmer" FOREIGN KEY ("source_confirmed_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer" ADD CONSTRAINT "fk_transfer_destination_confirmer" FOREIGN KEY ("destination_confirmed_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer_detail" ADD CONSTRAINT "fk_transfer_detail_transfer" FOREIGN KEY ("transfer_id") REFERENCES "warehouse_transfer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "warehouse_transfer_detail" ADD CONSTRAINT "fk_transfer_detail_request_detail" FOREIGN KEY ("request_detail_id") REFERENCES "warehouse_request_detail" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_lot_allocation" ADD CONSTRAINT "fk_transfer_allocation_detail" FOREIGN KEY ("transfer_detail_id") REFERENCES "warehouse_transfer_detail" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_lot_allocation" ADD CONSTRAINT "fk_transfer_allocation_lot" FOREIGN KEY ("inventory_lot_id") REFERENCES "inventory_lot" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "status_history" ADD CONSTRAINT "fk_status_history_actor" FOREIGN KEY ("changed_by_user_id") REFERENCES "app_user" ("id") DEFERRABLE INITIALLY IMMEDIATE;
